### ISSUE TITLE
Ajouter une section livrables à la page d'accueil

### ISSUE THREAD

**Issue by RadioPotin** [Decysif/website#16]

**Comment by claudemarche** [comment]
Je suggere de faire une page séparée pour les "productions" du projet, pour y mettre les livrables mais aussi les publis scientifiques. Pour ce qui est de la presentation des publis scientifiques, je ne suis pas fan du gros "bouton" a cliquer avec le titre de la publi dedans. Je suggere quelque chose de sans doute plus standard, cad sur l'exemple deja present : 
```
Paul Bonnot, Benoît Boyer, Florian Faissole, Claude Marché, Raphaël Rieu-Helft. Formally Verified Rounding Errors of the Logarithm-Sum-Exponential Function. Formal Methods in Computer-Aided Design, 2024. <a href="https://inria.hal.science/hal-04674600">paper on HAL</a>
```

**Comment by RadioPotin** [comment]
Bonjour Claude, entendu je vais prendre tout ça en considération, je reviens vers vous bientôt :)
